DungeonFinder/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from DungeonFinder import settings
from DungeonFinder.common.views import handle_404, index

handler404 = handle_404

urlpatterns = [
    path('', index, name='dashboard'),
    path('admin/', admin.site.urls),
    path('', include('DungeonFinder.users.urls')),
    path('', include('DungeonFinder.games.urls')),
    path('', include('DungeonFinder.messaging.urls')),
]

if not settings.LIVE and (settings.DEBUG or settings.TESTING):  # pragma: no cover
    from django.views.static import serve

    urlpatterns += [
        re_path(
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'), serve, kwargs={'document_root': settings.MEDIA_ROOT}
        )
    ]

DungeonFinder/users/urls.py
from django.urls import path

from DungeonFinder.users import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='profile-edit'),
    path('player/<str:screen_name>/', views.player_profile, name='player-profile'),
    path('gm/<str:screen_name>/', views.gm_profile, name='gm-profile'),
    path('signup/', views.user_signup, name='signup'),
    path('signup/pending/', views.signup_pending, name='signup-pending'),
    path('signup/confirm/<str:key>/', views.signup_confirm, name='signup-confirm'),
    path('themes/', views.user_update_theme, name='user-themes'),
]

DungeonFinder/games/models.py
from html import escape

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q, QuerySet
from django.urls import reverse


class CampaignQueryset(QuerySet):
    def request_joined_qs(self, request, as_player=False):
        if not request.user.is_authenticated:
            return self.none()
        elif request.user.is_admin:
            return self.all()
        else:
            query = Q(players=request.user)
            if not as_player and request.user.is_gm:
                query |= Q(creator=request.user.gamemaster)
            return self.filter(query).distinct()


class Campaign(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_COLD = 'cold'
    STATUS_IN_PROGRESS = 'in-progress'
    STATUS_FINISHED = 'finished'

    STATUS_CHOICES = (
        (STATUS_PENDING, 'Not started yet'),
        (STATUS_COLD, 'Gone cold'),
        (STATUS_IN_PROGRESS, 'In progress'),
        (STATUS_FINISHED, 'Finished'),
    )
    STATUS_JOINABLE = [STATUS_PENDING, STATUS_IN_PROGRESS]
    TYPE_HOMEBREW = 'homebrew'
    TYPE_MODULAR = 'modular'
    TYPE_SOURCE_BOOK = 'source-book'
    TYPE_CHOICES = (
        (TYPE_HOMEBREW, 'Homebrew'),
        (TYPE_MODULAR, 'Modular'),
        (TYPE_SOURCE_BOOK, 'Campaign Source Book'),
    )
    RP_ANY = 'any'
    RP_HEAVY = 'heavy'
    RP_LIGHT = 'light'
    RP_CHOICES = ((RP_ANY, 'Any'), (RP_LIGHT, 'light'), (RP_HEAVY, 'heavy'))

    objects = CampaignQueryset.as_manager()

    name = models.CharField(max_length=255)

    accepting_players = models.BooleanField(default=True)
    beginners_welcome = models.BooleanField(default=True)
    campaign_type = models.CharField(choices=TYPE_CHOICES, default=TYPE_HOMEBREW, max_length=20)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    creator = models.ForeignKey('users.GameMaster', on_delete=models.CASCADE, editable=False)
    description = models.TextField(null=True, blank=True)
    players = models.ManyToManyField('users.User', related_name='campaigns', blank=True, editable=False)
    mature_content = models.BooleanField('Contains mature content', default=False)
    max_players = models.IntegerField(default=5, validators=[MinValueValidator(1)])
    next_game_dt = models.DateTimeField(null=True, blank=True)
    price_per_session = models.DecimalField(
        help_text='The price per player per session.', decimal_places=2, max_digits=4, null=True, blank=True
    )
    role_play_level = models.CharField(choices=RP_CHOICES, default=RP_ANY, max_length=20)
    status = models.CharField(choices=STATUS_CHOICES, max_length=20, default=STATUS_PENDING, editable=False)

    def __str__(self):
        return self.name

    def game_full(self):
        return self.players.count() >= self.max_players

    def get_absolute_url(self):
        return reverse('campaign-details', kwargs={'pk': self.pk})

    def get_list_data(self):
        return {
            'name': escape(self.name),
            'link': self.get_absolute_url(),
            'free_spaces': self.free_spaces,  # This has been annotated onto the queryset
            'description': escape(self.description),
            'price_per_session': self.price_per_session,
        }

DungeonFinder/users/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.conf import settings
from django.contrib.auth.password_validation import validate_password

from DungeonFinder.common.forms import DFForm, DFModelForm
from DungeonFinder.users.models import User


class NewPasswordField(forms.CharField):
    widget = forms.PasswordInput

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    def widget_attrs(self, widget):
        return {'minlength': str(settings.PASSWORD_MIN_LENGTH)}

    def validate(self, value):
        super().validate(value)
        validate_password(value, user=self.user)


class SimplePasswordField(forms.CharField):
    widget = forms.PasswordInput


class UserSignupForm(DFModelForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput)
    password1 = NewPasswordField(
        label='Password',
        help_text=(
            f'Should be at least {settings.PASSWORD_MIN_LENGTH} characters long and '
            f'contain at least one letter and one number'
        ),
    )
    password2 = SimplePasswordField(label='Confirm password')
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    captcha = ReCaptchaField()

    def clean_email(self):
        return self.cleaned_data['email'].lower()

    def clean_password2(self):
        if (
            'password1' in self.cleaned_data
            and 'password2' in self.cleaned_data
            and self.cleaned_data['password1'] != self.cleaned_data['password2']
        ):
            raise forms.ValidationError('You must type the same password each time.')

    class Meta:
        model = User
        fields = 'email', 'first_name', 'last_name', 'screen_name'


class UserUpdateThemeForm(DFForm):
    themes = [
        ('theme-dark-red', 'Dark Red'),
        ('theme-dark-blue', 'Dark Blue'),
        ('theme-light-red', 'Light Red'),
        ('theme-light-blue', 'Light Blue'),
    ]
    theme = forms.ChoiceField(widget=forms.RadioSelect, choices=themes)


class UserProfileForm(DFModelForm):
    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'screen_name', 'avatar'

    def clean_screen_name(self):
        if User.objects.filter(screen_name__iexact=self.cleaned_data['screen_name']).exists():
            raise forms.ValidationError('A user with that screen name already exists')
        return self.cleaned_data['screen_name']

DungeonFinder/users/views.py
from django.contrib import messages
from django.contrib.auth import login as dj_login, logout as dj_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, TemplateView

from DungeonFinder.actions.models import Action, record_action
from DungeonFinder.common.views import DFEditView, DFFormView, DFView, generate_random_key
from DungeonFinder.messaging.emails import EmailRecipient, EmailTemplate, UserEmail, send_email
from DungeonFinder.users.forms import UserProfileForm, UserSignupForm, UserUpdateThemeForm
from DungeonFinder.users.models import GameMaster, User


class GMRequestMixin:
    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_gm):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class Login(LoginView):
    form_title = "Welcome Back"
    button_label = "Login"
    template_name = 'def-form.jinja'
    title = 'Login'
    form_class = AuthenticationForm
    redirect_authenticated_user = True

    def form_valid(self, form):
        r = super().form_valid(form)
        record_action(self.request.user, Action.ACTION_LOGIN)
        return r

    def get_redirect_url(self):
        return reverse('dashboard')

    def get_context_data(self, **kwargs):
        return super().get_context_data(title=self.title, **kwargs)


login = Login.as_view()


class Logout(LogoutView):
    template_name = 'base.jinja'

    def dispatch(self, request, *args, **kwargs):
        record_action(request.user, Action.ACTION_LOGOUT)
        dj_logout(request)
        return redirect(request.META.get('HTTP_REFERER', '/'))


logout = Logout.as_view()


class SignupPending(TemplateView):
    """
    Shown to the user after they sign up to tell them to confirm the link in their emails
    """

    template_name = 'users/signup-pending.jinja'


signup_pending = SignupPending.as_view()


class UserSignUp(DFFormView):
    form_title = "Sign Up"
    button_label = "Create Profile"
    template_name = 'def-form.jinja'

    form_class = UserSignupForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        data = {k: v for k, v in form.cleaned_data.items() if k not in {'password1', 'password2', 'captcha'}}
        data['password'] = make_password(form.cleaned_data['password1'])
        key = generate_random_key()
        cache.set('signup-' + key, data, 86400 * 7)  # store in cache for 1 week
        confirm_link = reverse('signup-confirm', kwargs={'key': key})
        send_email.delay(
            UserEmail(
                recipient=EmailRecipient(
                    email=data['email'],
                    first_name=data['first_name'],
                    last_name=data['last_name'],
                ),
                context={'confirm_link': confirm_link},
                template_type=EmailTemplate.TEMPLATE_SIGNUP,
            )
        )
        return redirect('signup-pending')


user_signup = UserSignUp.as_view()


def signup_confirm(request, key):
    cache_key = 'signup-' + key
    data = cache.get(cache_key)
    if data is None:
        messages.error(
            request,
            (
                'That link is invalid. Either it has been used already, or it has expired. '
                'You can create your account again from the sign up form'
            ),
        )
        return redirect('dashboard')
    cache.delete(cache_key)
    try:
        user = User.objects.create(**data)
    except IntegrityError:
        messages.error(
            request,
            'A user already exists with either that Email address or screen name. Please try signing up again',
        )
        return redirect('dashboard')
    else:
        dj_login(request, user)
        messages.success(request, 'Account successfully created.')
        record_action(user, Action.ACTION_SIGNUP)
        return redirect(data.get('next') or '/')


class UserUpdateProfile(LoginRequiredMixin, DFEditView):
    model = User
    form_class = UserProfileForm
    form_title = 'Edit Profile'
    button_label = 'Update Profile'
    template_name = 'def-form.jinja'
    success_url = reverse_lazy('dashboard')
    action = Action.ACTION_EDIT_PROFILE

    def get_object(self, queryset=None):
        return self.request.user


edit_profile = UserUpdateProfile.as_view()


class UserProfile(DetailView):
    model = User
    template_name = 'users/profile.jinja'

    def get_object(self, queryset=None):
        return self.request.user


user_profile = UserProfile.as_view()


class GMSignUp:
    pass


class GMProfileUpdate:
    pass


class UserUpdateTheme(LoginRequiredMixin, DFFormView):
    model = User
    form_class = UserUpdateThemeForm
    template_name = 'users/themes.jinja'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        theme = form.cleaned_data['theme']
        self.request.user.user_theme = theme  # Get the data from the form
        self.request.user.save()  # and save
        messages.success(self.request, 'Well done, you did good editing')  # Displaying the nice message to the user
        return redirect('dashboard')  # Not sure where you want to return the user to after, but this is where you say


user_update_theme = UserUpdateTheme.as_view()


class PlayerProfile(DFView, DetailView):
    model = User
    context_object_name = 'player'
    template_name = 'users/player-profile.jinja'
    slug_field = slug_url_kwarg = 'screen_name'

    def get_meta_title(self):
        return self.get_object().screen_name


player_profile = PlayerProfile.as_view()


class GameMasterProfile(DFView, DetailView):
    model = GameMaster
    template_name = 'users/gm-profile.jinja'
    slug_field = 'user__screen_name'
    slug_url_kwarg = 'screen_name'

    def get_meta_title(self):
        return self.get_object().user.screen_name


gm_profile = GameMasterProfile.as_view()

templates/users/dashboard.jinja
{% extends 'base.jinja' %}

{% block content %}
<section class="pb-20 flex items-center">
	<div class="container mx-auto">
		<div class="pt-10">
			<div class="mb-10">
				<div class="hr-icon">
					<img src="/static/img/helmet.svg" alt="">
				</div>
				<hr class="hr-text text-xl leading-7" data-content="Joined Campaigns">
				{% if user.campaigns.count() == 0 %}
					<div class="text-center">
						<h2 class="mb-6">You haven't joined any games yet, click here to view all games.</h2>
						<a href="{{ url('avail-campaign-list')}}" class="btn">View Games</a>
					</div>
				{% else %}
					<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-3 pb-20 px-10">
					{% for camp in user.campaigns.all() %}
						{% include "/partials/camp_list.jinja" %}
					{% endfor %}
					</div>
				{% endif %}
			</div>
			{% if user.gamemaster %}
			<div class="mb-10">
				<div class="hr-icon">
					<img src="/static/img/helmet.svg" alt="">
				</div>
				<hr class="hr-text text-xl leading-7" data-content="Hosted Campaigns">
				<div class="text-center">
				{% if user.gamemaster.campaign_set.all().count() == 0 %}
					<h2 class="mb-6">You haven't created any games yet, click here to view all games.</h2>
					<a href="{{ url('avail-campaign-list')}}" class="btn">Search Games</a>
				{% else %}
					<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-3 pb-20 px-10">
					{% for camp in user.gamemaster.campaign_set.all() %}
						{% include "/partials/camp_list.jinja" %}
					{% endfor %}
					</div>
					<a href="{{ url('campaign-create')}}" class="btn">Create Campaign</a>
				{% endif %}
				</div>
			</div>
			{% endif %}
		</div>
	</div>
</section>
{% endblock %}

templates/users/gm-profile.jinja
{% extends 'base.jinja' %}

{% block content %}
  {{ gm }}
{% endblock %}

templates/users/player-profile.jinja
{% extends 'base.jinja' %}

{% block content %}
  {{ player }}
{% endblock %}

templates/users/profile.jinja
{% extends 'base.jinja' %}

{% block content %}
<section class="pt-32 pb-10 text-white" id="overview">
  <div class="container mx-auto text-center">
    <p>{{ user.first_name }}</p>
    <p>{{ user.last_name }}</p>
    <p>{{ user.screen_name }}</p>
    {% if user.avatar %}
      <p><img src="{{ user.avatar | thumbnail_url('lg') }}"></p>
    {% endif %}
  </div>
</section>
{% endblock %}

templates/users/reset_password.jinja
{% extends 'base.jinja' %}

templates/users/signup-pending.jinja
{% extends 'base.jinja' %}

{% block content %}
  <p>Confirm your account by clicking the link in the email you received</p>
{% endblock %}

templates/users/themes.jinja
{% extends 'base.jinja' %}

{% block content %}
<section class="pb-20 pt-20 px-4 text-center flex items-center">
	<div class="w-full max-w-5xl mx-auto">
		<h2 class="text-4xl leading-tight font-heading">Choose your style</h2>
		<p class="text-xl mt-2">
			Change your theme and colours below. <br/>Don't worry, you can change these at any time.
		</p>
		<form method="post" style="background: transparent;">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			<div class="py-10 grid grid-cols-3 grid-s gap-3">
				{% for radio in form.theme %}
				<label class="theme-option" data-theme="{{radio.data.value}}">
        	<span class="hidden">{{ radio }}</span>
					<img src="/static/img/theme-red.png">
					<div class="mt-1">
						{{ radio.data.label }}
					</div>
				</label>
				{% endfor %}
			</div>
			<button class="btn btn-primary" type="submit">Save</button>
		</div>
	</form>
</div>
</div>
</section>
{% endblock %}